export const MAX_ATTEMPTS = 7;
export const PER_TURN_GAME_DURATION = 2;
export const roomNames = [
  'Mina is Awesome',
  'Mina is Amazing',
  'Mastermind Mina',
  'Mina Mania',
  'Codebreakers Unite',
  'Secret Code Vault',
  'The Puzzle Palace',
  'Mina Mystery Room',
  'ZK Challenge',
  'Brain Teaser Arena',
  'Clue Hunters',
  'Cipher Central',
  'Mina Mind Games',
  'The Hidden Code',
  'Logic Lab',
  'The Enigma Chamber',
  'Code Quest',
  'Mina Magic',
  'Puzzle Masters',
  'The Brain Cave',
  'ZK Zone',
  'Clue Kingdom',
  'Secret Cipher',
  'Mystery Mansion',
  'The Logic Lounge',
  'Code Commanders',
  'Mina Matrix',
  'The Puzzle Pit',
  'Brainstorm Bay',
  'Mind Maze',
  'Cipher City',
  'Logic Legends',
  'Mina Mind Palace',
  'The Hidden Vault',
  'Riddle Realm',
  'Secret Strategy',
  'The Enigma Engine',
  'Code Conundrum',
  'Puzzle Pioneers',
  'The Brain Bunker',
  'Mina Minds Unite',
  'Logic Labyrinth',
  'The Cryptic Corner',
  'Cipher Challenge',
  'Mastermind Manor',
  'The Puzzle Parlor',
  'Clue Castle',
  'Hidden Hints',
  'Mind Masters',
  'The Enigma Emporium',
  'Secret Signals',
  'The Puzzle Plaza',
  'Brain Boosters',
  'Mina Mystery Maze',
  'The Cipher Chamber',
  'Code Craze',
  'Logic Legends Arena',
  'Puzzle Pros',
  'The Brain Bazaar',
  'Clue Coliseum',
  'Mystery Masters',
  'The Hidden Hall',
  'Code Champions',
  'Cipher Citadel',
  'Mina Mind Maze',
  'The Logic Loft',
  'Riddle Raiders',
  'Puzzle Palace Arena',
  'Secret Seekers',
  'The Brain Bridge',
  'Mind Mission',
  'The Enigma Estate',
  'Code Crusaders',
  'Logic Legends Lab',
  'Puzzle Planet',
  'The Clue Chamber',
  'Mina Mind Arena',
  'Cipher Cove',
  'The Mystery Market',
  'Brain Battleground',
  'Riddle Room',
  'Secret Sphere',
  'The Logic Lighthouse',
  'Puzzle Pavilion',
  'Clue Cove',
  'Mind Maze Arena',
  'The Enigma Edge',
  'Code Keepers',
  'Cipher Club',
  'Mina Mystery Mansion',
  'The Puzzle Port',
  'Logic Lab Arena',
  'Brain Blast',
  'Secret Strategy Room',
  'The Hidden Hub',
  'Riddle Realm Arena',
  'Code Castle',
  'Cipher Kingdom',
  'Mina Mind Club',
  'The Logic Labyrinth',
  'Puzzle Paradise',
  'Brain Bazaar Arena',
  'Clue Castle Arena',
  'Mystery Mansion Lab',
  'The Enigma Empire',
  'Code Craze Club',
];
export const MAX_ALLOWED_GAMES = 30
