/**
 * This file contains the core game service functions for handling player actions in the Mina Mastermind game.
 * It provides logic for joining games, submitting zkProofs, handling game start, penalization logic,
 * and resuming ongoing games on-chain.
 *
 */

import WebSocket from 'ws';
import {
  getGameById,
  createOrUpdateGame,
  deleteGame,
  resumeOnGoingGames,
} from './repositories/game.js';
import {
  MastermindZkApp,
  StepProgramProof,
  GameState,
  Clue,
} from 'stan-mastermind';
import { Queue } from 'bullmq';
import {
  fetchAccount,
  fetchLastBlock,
  Field,
  PublicKey,
  UInt32,
  VerificationKey,
  verify,
} from 'o1js';
import { GameStatus, IGame } from './models/Game.js';
import { MAX_ATTEMPTS, VERIFIED_REFEREES } from './constants.js';
import * as Sentry from '@sentry/node';

/**
 * Handles a player joining a game. Adds their WebSocket to the list of active players
 * and sends the latest proof and game state if available.
 *
 * @param gameId - The ID of the game the player is joining.
 * @param activePlayers - A map of active WebSocket connections by game ID.
 * @param ws - The WebSocket instance of the joining player.
 */
export const handleJoinGame = async (
  gameId: string,
  activePlayers: Map<string, Set<WebSocket>>,
  ws: WebSocket
) => {
  let game = await getGameById(gameId);
  let lastProof = game?.lastProof || null;
  let timestamp = game?.timestamp || null;
  if (!activePlayers.has(gameId)) {
    activePlayers.set(gameId, new Set());
  }
  activePlayers.get(gameId)?.add(ws);

  if (lastProof) {
    ws.send(JSON.stringify({ zkProof: lastProof, timestamp, game }));
  }
};

/**
 * Processes a received zkProof, verifies it, validates its turn count,
 * updates the game state, and schedules a final proof if the game is solved.
 *
 * @param gameId - The ID of the game.
 * @param zkProof - The serialized zkProof (JSON string).
 * @param receivedRewardAmount - The reward amount sent by the code master.
 * @param playerPubKeyBase58 - Public key of the player sending the proof.
 * @param refereePubKeyBase58 - Public key of the referee of the game.
 * @param activePlayers - A map of active WebSocket connections by game ID.
 * @param ws - The WebSocket instance of the sender.
 * @param gameLifecycleQueue - The BullMQ queue managing game lifecycle jobs.
 * @param vk - The verification key generated by compiling the StepProgram.
 */
export const handleProof = async (
  gameId: string,
  zkProof: string,
  receivedRewardAmount: number,
  playerPubKeyBase58: string,
  refereePubKeyBase58: string,
  activePlayers: Map<string, Set<WebSocket>>,
  ws: WebSocket,
  gameLifecycleQueue: Queue,
  vk: VerificationKey,
  roomName: string,
  gameCreationTransactionHash: string
) => {
  // Validate that a zkProof has been submitted
  if (!zkProof) {
    ws.send(JSON.stringify({ error: 'Missing zkProof!' }));
    return;
  }
  // Check whether the game should be penalized due to timeout exceeded
  let { game, isPenalized } = await checkForPenalization(
    gameId,
    gameLifecycleQueue
  );
  // If penalized, broadcast updated game state to all players
  if (isPenalized) {
    const players = activePlayers.get(gameId) || new Set();
    players.forEach((player: WebSocket) => {
      player.send(JSON.stringify({ game }));
    });
    return;
  }
  // Reject proof submission if the game is no longer in progress
  if (game && game.status !== GameStatus.IN_PROGRESS) {
    ws.send(JSON.stringify({ error: 'Not allowed to send a proof!' }));
    return;
  }

  // Extract the last proof from game state, if it exists
  let lastProof = game?.lastProof || null;
  let lastTurnCount = null;
  const gameRewardAmount = game?.rewardAmount || receivedRewardAmount;

  // Extract turn count from last proof if available
  if (lastProof) {
    const proof = await StepProgramProof.fromJSON(JSON.parse(lastProof));
    lastTurnCount = Number(proof.publicOutput.turnCount.toString());
  }

  // Variables for parsed proof and its properties
  let receivedProof;
  let turnCount, isSolved;
  let receivedTurnCount;

  // Deserialize and verify the submitted zkProof
  try {
    receivedProof = await StepProgramProof.fromJSON(JSON.parse(zkProof));
    const validProof = await verify(receivedProof, vk);

    // Throw an error if the proof is invalid
    if (!validProof) {
      throw new Error('Invalid zkProof!');
    }
  } catch (e) {
    console.error('Error verifying proof:', e);
    ws.send(JSON.stringify({ error: 'Invalid zkProof!' }));
    return;
  }
  // Extract the turn count from the verified proof
  receivedTurnCount = Number(receivedProof.publicOutput.turnCount.toString());

  // Reject if the submitted proof does not represent the next turn
  if (receivedTurnCount - (lastTurnCount || 0) !== 1) {
    ws.send(JSON.stringify({ error: 'Proof is outdated!' }));
    return;
  }

  // If it's the code master's turn (odd turn), check if game is solved
  if (receivedTurnCount % 2 !== 0 && receivedTurnCount > 1) {
    turnCount = Number(receivedProof.publicOutput.turnCount.toString());
    const deserializedClue = Clue.decompress(
      receivedProof.publicOutput.lastcompressedClue
    );
    isSolved = deserializedClue.isSolved().toBoolean();
  }

  // Determine the winner if game is solved or if max attempts are exceeded
  let winnerPublicKeyBase58 = null;
  if (isSolved || (turnCount && turnCount > MAX_ATTEMPTS * 2)) {
    winnerPublicKeyBase58 = isSolved ? game?.codeBreaker : game?.codeMaster;

    // Schedule a job to submit the final proof on-chain
    await gameLifecycleQueue.add(
      'sendFinalProof',
      {
        gameId,
        zkProof,
        winnerPublicKeyBase58,
      },
      { priority: 1 }
    );
  }
  const timestamp = Date.now();

  // Update game state in database with latest proof and related metadata
  const updatedGame = await createOrUpdateGame({
    _id: gameId,
    lastProof: zkProof,
    timestamp,
    rewardAmount: gameRewardAmount,
    codeMaster:
      lastTurnCount === null && playerPubKeyBase58
        ? playerPubKeyBase58
        : undefined,
    turnCount: receivedTurnCount,
    winnerPublicKeyBase58: winnerPublicKeyBase58
      ? winnerPublicKeyBase58
      : undefined,
    status: winnerPublicKeyBase58 ? GameStatus.ENDED : undefined,
    refereePubKeyBase58:
      lastTurnCount === null ? refereePubKeyBase58 : undefined,
    isRefereeVerified:
      lastTurnCount === null
        ? VERIFIED_REFEREES.includes(refereePubKeyBase58)
        : undefined,
    gameCreationTransactionHash:
      lastTurnCount === null ? gameCreationTransactionHash : undefined,
    roomName: lastTurnCount === null ? roomName : undefined,
  });

  // Notify all connected players in the game about the new proof and game state
  const players = activePlayers.get(gameId);
  players?.forEach((player: WebSocket) => {
    player.send(JSON.stringify({ zkProof, timestamp, game: updatedGame }));
  });
};

/**
 * Starts a game after validating that it has been accepted on-chain and meets all integrity checks.
 *
 * @param gameId - The id of the game.
 * @param activePlayers - Map tracking active WebSocket clients per game.
 * @param ws - WebSocket instance of the sender.
 * @param gameLifecycleQueue - Queue to trigger background jobs.
 * @param verificationKeyHash - Hash of the verification key generated by compiling the contract.
 *
 * @throws Will notify the client if the game is not accepted or not compliant with the expected zkApp.
 */
export async function handleGameStart(
  gameId: string,
  activePlayers: Map<string, Set<WebSocket>>,
  ws: WebSocket,
  gameLifecycleQueue: Queue,
  verificationKeyHash: Field
) {
  // Fetch the current game from the database
  const game = await getGameById(gameId);

  // Only proceed if the game has not started yet (no codeBreaker)
  if (!game?.codeBreaker) {
    const zkAppPublicKey = PublicKey.fromBase58(gameId);
    const zkApp = new MastermindZkApp(zkAppPublicKey);

    // Ensure the zkApp account exists on chain
    let res = await fetchAccount({ publicKey: zkAppPublicKey });
    if (!res.account) {
      ws.send(JSON.stringify({ error: 'Game has not been accepted!' }));
      return;
    }

    // Verify the on-chain contract's verification key matches the expected one
    const vk = res.account?.zkapp?.verificationKey?.hash;
    if (vk?.toString() !== verificationKeyHash.toString()) {
      await deleteGame(gameId);
      ws.send(
        JSON.stringify({ error: 'Game is not using the verified contract!' })
      );
      return;
    }

    // Check if the `gameAccepted` event has been emitted on chain
    const zkAppEvents = await zkApp.fetchEvents(UInt32.from(0));
    const acceptGameEvent = zkAppEvents.find((e) => e.type === 'gameAccepted');
    if (!acceptGameEvent) {
      ws.send(JSON.stringify({ error: 'Game has not been accepted!' }));
      return;
    }

    // Extract data from the acceptance event
    const acceptedGame = JSON.parse(JSON.stringify(acceptGameEvent.event.data));

    // Check whether the game started on-chain in time, otherwise penalize
    const latestBlock = await fetchLastBlock(
      process.env.MINA_NETWORK_URL as string
    );
    const currentSlot = Number(latestBlock.globalSlotSinceGenesis.toString());
    const finalizeSlot = Number(acceptedGame.finalizeSlot);
    const startGameSlot = finalizeSlot - 2 * (MAX_ATTEMPTS || 0);
    let status = GameStatus.IN_PROGRESS;
    let winnerPublicKeyBase58 = null;

    // If more than 4 slots have passed since the expected start, penalize the code breaker
    if (currentSlot - startGameSlot > 4) {
      await gameLifecycleQueue.add(
        'forfeitWin',
        {
          gameId,
          winnerPublicKeyBase58: game?.codeMaster,
        },
        { priority: 1 }
      );
      status = GameStatus.PENALIZED;
      winnerPublicKeyBase58 = game?.codeMaster;
    }

    // Check if the game has already started on chain
    const { turnCount } = GameState.unpack(await zkApp.compressedState.get());
    if (Number(turnCount.toString()) > 1) {
      const updatedGame = await createOrUpdateGame({
        _id: gameId,
        codeBreaker: acceptedGame.codeBreakerPubKey,
        status: GameStatus.ON_CHAIN,
        timestamp: Date.now(),
      });

      // Notify all connected players
      const players = activePlayers.get(gameId) || new Set();
      players.forEach((player: WebSocket) => {
        player.send(JSON.stringify({ game: updatedGame }));
      });
      return;
    }

    // Create or update the game in DB with the latest metadata
    const updatedGame = await createOrUpdateGame({
      _id: gameId,
      codeBreaker: acceptedGame.codeBreakerPubKey,
      status,
      timestamp: Date.now(),
      winnerPublicKeyBase58: winnerPublicKeyBase58
        ? winnerPublicKeyBase58
        : undefined,
    });

    // Broadcast updated game state
    const players = activePlayers.get(gameId) || new Set();
    players.forEach((player: WebSocket) => {
      player.send(JSON.stringify({ game: updatedGame }));
    });
    return;
  }

  // Reject if the game is already marked as started
  ws.send(JSON.stringify({ error: 'Game has already started!' }));
}

/**
 * Attempts to penalize a player if they exceeded their allowed response time.
 * If a penalty has been applied, notifies all connected players in the game.
 * If no penalty is needed or it's already applied, informs the requesting client.
 *
 * @param gameId - The ID of the game to start.
 * @param activePlayers - A map of active WebSocket connections by game ID.
 * @param ws - The WebSocket instance of the requester.
 * @param gameLifecycleQueue - The BullMQ queue used to trigger game jobs.
 */
export async function handlePenalize(
  gameId: string,
  activePlayers: Map<string, Set<WebSocket>>,
  ws: WebSocket,
  gameLifecycleQueue: Queue
) {
  // Check if the game meets the criteria for penalization due to turn timeout
  const { isPenalized, game } = await checkForPenalization(
    gameId,
    gameLifecycleQueue
  );

  if (isPenalized) {
    // Broadcast the updated game state to all connected players
    const players = activePlayers.get(gameId) || new Set();
    players.forEach((player: WebSocket) => {
      player.send(JSON.stringify({ game }));
    });
  } else if (!isPenalized && game?.status === GameStatus.PENALIZED) {
    // If the game is already marked as penalized
    ws.send(JSON.stringify({ error: 'Player is already penalized!' }));
  } else {
    // Game is still active and within time limits
    ws.send(
      JSON.stringify({ error: 'Player did not exceeded the allowed time!' })
    );
  }
}

/**
 * Triggers a penalty check.
 * If the game exceeded its allowed turn duration, it penalizes the appropriate player
 * and updates the game state.
 *
 * @param gameId - The ID of the game to check.
 * @param activePlayers - A map of active WebSocket connections by game ID.
 * @param ws - The WebSocket instance of the requester.
 * @param gameLifecycleQueue - The BullMQ queue to schedule the forfeit job.
 * @returns {Promise<{isPenalized:boolean,game:IGame | null }>}
 */
async function checkForPenalization(
  gameId: string,
  gameLifecycleQueue: Queue
): Promise<{ isPenalized: boolean; game: IGame | null }> {
  const now = Date.now();
  const game = await getGameById(gameId);

  // Skip penalization check if the game is not currently in progress
  if (game?.status !== GameStatus.IN_PROGRESS) {
    return {
      isPenalized: false,
      game,
    };
  }
  const lastTurnTimestamp = game?.timestamp || Date.now();

  // Define max allowed turn duration (2.5 minutes in milliseconds)
  const TURN_DURATION = 1000 * 60 * 2.5;

  // Check if time since last move exceeds allowed duration
  if (game?.turnCount && now - lastTurnTimestamp > TURN_DURATION) {
    // Determine the winner based on whose turn it was
    const winnerPublicKeyBase58 =
      game?.turnCount % 2 === 0 ? game?.codeBreaker : game?.codeMaster;
    // Update game status to penalized and store the winner
    const updatedGame = await createOrUpdateGame({
      _id: gameId,
      status: GameStatus.PENALIZED,
      winnerPublicKeyBase58,
    });
    console.log('Penalizing game : ', gameId);

    // Enqueue a job to process the penalty on-chain
    await gameLifecycleQueue.add(
      'forfeitWin',
      {
        gameId,
        winnerPublicKeyBase58,
      },
      { priority: 1 }
    );
    return {
      isPenalized: true,
      game: updatedGame,
    };
  }
  // No penalty
  return {
    isPenalized: false,
    game,
  };
}

/**
 * Updates all games with status `IN_PROGRESS` to `ON_CHAIN` after a server restart.
 *
 * This function is called during server startup to handle the recovery of ongoing games
 * that were being played before a server outage. Since in-progress games rely on server-side
 * state and timers, resuming them after an outage is unreliable.
 *
 * To ensure uninterrupted gameplay, this function promotes such games to `ON_CHAIN` status,
 * allowing players to continue the game through Mina smart contract interactions directly.
 *
 *
 * @returns {Promise<void>} Resolves when all valid games are migrated to on-chain mode.
 * @throws Logs an error if the migration process encounters issues.
 */
export async function resumeOnChain(): Promise<void> {
  try {
    await resumeOnGoingGames();
  } catch (err) {
    console.log('error resuming games on chain: ', err);
    Sentry.captureException(err);
    throw err;
  }
}
