FROM node:20-slim AS deps

WORKDIR /app

COPY integration-test/package.json ./
COPY yarn.lock ./
RUN yarn --check-files

FROM node:20-slim AS builder

WORKDIR /app

ADD integration-test/ .
COPY --from=deps /app/node_modules/ /app/node_modules/
COPY --from=deps /app/package.json /app/yarn.lock  /app/
CMD ["yarn", "dev"]
